spring.application.name=authservice
server.port=9000

spring.datasource.url=jdbc:mysql://localhost:3306/auth_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

user.service.url=http://localhost:8083
auth.issuer=http://127.0.0.1:9000
auth.oauth-client-id=gateway-client
auth.oauth-client-secret=secret
auth.oauth-redirect-uri=http://localhost:8080/login/oauth2/code/authservice
auth.signing-key-path=.local/authservice-ec-key.json
auth.signing-key-jwk=

logging.level.org.springframework.security=TRACE
logging.level.org.springframework.security.oauth2=TRACE
logging.level.org.springframework.security.web=TRACE
logging.level.org.springframework.security.oauth2.server.authorization=TRACE
