spring.application.name=messageservice
server.port=8081

spring.datasource.url=jdbc:mysql://localhost:3306/messages_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.publisher-confirm-type=correlated

spring.grpc.client.default-channel.address=localhost:8083
spring.grpc.client.default-channel.secure=false

logging.level.org.example.messageservice=DEBUG
