spring.application.name=bff
server.port=8080

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:9000/auth/jwks

auth.service.url=http://localhost:9000
user.service.url=http://localhost:8083
message.service.url=http://localhost:8081
internal.api-key=labb2-dev-internal-key
