spring.application.name=bff
server.port=8080
spring.config.import=optional:configtree:/run/secrets/

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:9000/auth/jwks}

auth.service.url=${AUTH_SERVICE_URL:http://localhost:9000}
user.service.url=${USER_SERVICE_URL:http://localhost:8083}
message.service.url=${MESSAGE_SERVICE_URL:http://localhost:8081}
internal.api-key=${INTERNAL_API_KEY}
