FROM paketobuildpacks/ubuntu-noble-run-tiny:0.0.87
WORKDIR /workspace
COPY target/native-runtime/ ./
ENV LD_LIBRARY_PATH=/workspace
EXPOSE 9000
ENTRYPOINT ["./org.example.authservice.AuthserviceApplication"]
